# Generated by Django 5.2.17 on 2026-09-10 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("place", models.CharField(blank=True, max_length=200)),
                ("aadhar_number", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("GPAY", "GPay"),
                            ("CARD", "Card"),
                            ("BANK", "Bank transfer"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Material categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("payee", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("GPAY", "GPay"),
                            ("CARD", "Card"),
                            ("BANK", "Bank transfer"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_label",
                    models.CharField(help_text='e.g. "12 inch 8 ft"', max_length=100),
                ),
                (
                    "ft_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Length in feet, used in bill amount calc",
                        max_digits=8,
                    ),
                ),
                (
                    "default_rate_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("total_stock_count", models.PositiveIntegerField(default=0)),
                ("available_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="rentals.materialcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "size_label"],
            },
        ),
        migrations.CreateModel(
            name="ProductPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("size_label", models.CharField(blank=True, max_length=100)),
                ("count", models.PositiveIntegerField()),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="rentals.materialcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=30, unique=True)),
                ("date_out", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PARTIALLY_RETURNED", "Partially returned"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_transactions",
                        to="rentals.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_out", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentalLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("days_estimated", models.PositiveIntegerField(default=1)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("count_returned", models.PositiveIntegerField(default=0)),
                ("date_returned", models.DateField(blank=True, null=True)),
                ("days_actual", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_lines",
                        to="rentals.material",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="rentals.rentaltransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("GPAY", "GPay"),
                            ("CARD", "Card"),
                            ("BANK", "Bank transfer"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="rentals.rentaltransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DepositLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "amount_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_refunded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_entries",
                        to="rentals.rentaltransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUT", "Out (rented)"), ("IN", "In (returned)")],
                        max_length=3,
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="rentals.material",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="rentals.rentaltransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
